### PR TITLE
WIP: update to golang 1.13 and go mod

### PR DESCRIPTION
**Pull request by glower**
* changed go version in travis and docker

### CODE REVIEW

**Comment by glower** [comment]
* Tests are green, don't know why test coverage drops
* Build on travis works
* Docker-compose works (added database migration step to it)
* Snap build is not working, but it's not working on master also, I don't think it's used

**Comment by doismellburning** [comment]
There's a bunch going on here - thoughts on splitting it for easier reviewability?

**Comment by glower** [comment]
> There's a bunch going on here - thoughts on splitting it for easier reviewability?

I can put docker/makefile in one PR, changes for snapcraft in another PR and go mod/fixes for travis to a 3rd one to make it smaller and than tag it as a new release.

**Comment by glower** [comment]
Snap build is fixed now, I will split this PR

**Comment by glower** [comment]
Because we can't pin to the previous version of the snapd we will postpone the update

**Pull request closed without merging**
